# docker-Specify the compose version
version: "3"

services:
  app:
    # build: .
    image: pudding/docker-image-base:action-Podcast-Filter-Docker-Image-20240803.033424
    tty: true
    volumes: 
      - ./output:/output/
      - ./cache:/cache/
      - ./config.js:/config.js
      - ./config-list.js:/config-list.js
      - ./config-json.js:/config-json.js